# Dean Scarff's helix config.

[editor]
auto-completion = false
auto-pairs = false

[editor.lsp]
auto-signature-help = false

[keys.insert]
"C-a" = "normal_mode"

[keys.select]
"C-a" = "normal_mode"

[keys.normal]
# Don't comment things when trying to dismiss popups.
"C-c" = "no_op"
# Some vim habits die hard.
Z = { Z = ":write-quit", Q = ":quit!" }
