# Dean Scarff's helix config.

theme = "base16_default"

[editor]
auto-completion = false
auto-pairs = false

[editor.gutters]
layout = ["line-numbers", "spacer"]

[editor.lsp]
auto-signature-help = false

[keys.insert]
"C-a" = "normal_mode"

[keys.select]
"C-a" = "normal_mode"

[keys.normal]
# Don't comment things when trying to dismiss popups.
"C-c" = "no_op"

# Swap join-selections around since A-J is awkward and I almost always want
# to delete the space afterwards.
"J" = "join_selections_space"
"A-J" = "join_selections"

# Some vim habits die hard.
Z = { Z = ":write-quit", Q = ":quit!" }
